<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [1]:
import numpy as np

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [3]:
py_list = ["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]

In [4]:
py_list[0]

'a1'

In [5]:
py_list[-1]

'j10'

In [6]:
py_list[0:3]

['a1', 'b2', 'c3']

In [7]:
py_list[1:3]

['b2', 'c3']

In [8]:
py_list[1:6]

['b2', 'c3', 'd4', 'e5', 'f6']

In [9]:
py_list[1:6:2]

['b2', 'd4', 'f6']

In [10]:
py_list[5:]

['f6', 'g7', 'h8', 'i9', 'j10']

In [11]:
py_list[5::2]

['f6', 'h8', 'j10']

In [12]:
py_list[:5]

['a1', 'b2', 'c3', 'd4', 'e5']

In [14]:
py_list[5:2:-1]

['f6', 'e5', 'd4']

In [15]:
py_list[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [16]:
py_list[::-2]

['j10', 'h8', 'f6', 'd4', 'b2']

## 1.2 Arrays only | Subsetting by masking

In [18]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [21]:
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [22]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [24]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

**Example 1**

In [26]:
np_array[~(np_array > 3)]  # "~" is the Bitwise Not operator

array([1, 2, 3])

**Example 2**

In [27]:
np_array[(np_array > 3) & (np_array < 8)]  # "&" is the Bitwise And

array([4, 5, 6, 7])

**Example 3**

In [28]:
np_array[(np_array < 3) | (np_array > 8)]

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [29]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

**Example 1**

In [30]:
py_list_2d[3]

[4, 'D']

In [31]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

**Example 2**

In [32]:
py_list_2d[3][0]

4

In [33]:
np_array_2d[3, 0]

'4'

**Example 3**

In [35]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [36]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

**Example 4**

In [39]:
py_list_2d[:3][0]

[1, 'A']

In [40]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

**Example 5**

In [41]:
py_list_2d[3:6][0]

[4, 'D']

In [42]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [43]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

**Example 1**

In [46]:
x = [1, 2] * 5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

**Example 2**

In [53]:
x = [1]
x = x + [2]
x = x + [3]
x = x + [4]
x

[1, 2, 3, 4]

In [54]:
x = [1]
x += [2]
x += [3]
x += [4]
x

[1, 2, 3, 4]

In [56]:
x = [1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

**Example 3**

In [57]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [3]:
x = [1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [5]:
x = [1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

In [6]:
[1, 4, 5] + x

[1, 4, 5, 1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [65]:
a = [1, 2, 3, 4, 5]
a[0] = 1233452
a

[1233452, 2, 3, 4, 5]

In [7]:
# Defining a tuple
a_tuple = (1, 2, 3)

In [68]:
print(a_tuple[0])

1


In [69]:
# Will not work
a_tuple[0] = -1
a_tuple[0] += [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [77]:
# Do not do this - y and z are not different
x = [1, 2, 3]
y = x
z = x

In [79]:
print(f"{id(x)=}, {id(y)=}, {id(z)=}")

id(x)=4447605376, id(y)=4447605376, id(z)=4447605376


In [80]:
x = [1, 2, 3]
y = x.copy()
z = x.copy()

In [81]:
print(f"{id(x)=}, {id(y)=}, {id(z)=}")

id(x)=4447842944, id(y)=4447453760, id(z)=4447610048
