<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [53]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

**Python Lists**

In [54]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**NumPy Arrays**

In [55]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

**Dictionary**

In [56]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [57]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Example 1**

In [58]:
py_real_names[0]

'Natasha Romanoff'

**Example 2**

In [59]:
py_super_names[0]

'Black Widow'

In [60]:
i = 2
print(py_real_names[i], "is", py_super_names[i])

Stephen Strange is Doctor Strange


**Example 3**

In [61]:
py_super_names[2]

'Doctor Strange'

In [62]:
py_super_names[-1]

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [63]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [64]:
superhero_info["Tony Stark"]

'Iron Man'

In [65]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [66]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [67]:
py_superhero_info = [
    ["Natasha Romanoff", "Black Widow"],
    ["Tony Stark", "Iron Man"],
    ["Stephen Strange", "Doctor Strange"]
]

# 2 Lists vs. Arrays

In [68]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)     

In [69]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [70]:
np_array_2d  # A NumPy array can only hold a single type

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

## 2.1 Size

**Lists**

In [71]:
len(py_list_2d)

10

**Arrays**

In [72]:
len(np_array_2d)

10

In [73]:
np_array_2d.shape  # property or attribute of the NumPy array

(10, 2)

## 2.2 Arrays are fussy about type

In [74]:
py_list = [1, 1.5, "A"]
np_array = np.array(py_list)

**Lists**

In [75]:
py_list

[1, 1.5, 'A']

**Arrays**

In [76]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [77]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)      

**Lists**

In [78]:
py_list + 10  # Will not work

TypeError: can only concatenate list (not "int") to list

**Arrays**

In [ ]:
np_array + 10

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [ ]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

**Lists**

In [ ]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

**Arrays**

In [ ]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)      

**Lists**

In [ ]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

**Arrays**

In [ ]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

**Lists**

In [ ]:
py_list**2  # Will not work

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

**Arrays**

In [ ]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)      

**Lists**

**Example 1**

In [ ]:
py_list == 3

False

**Example 2**

In [ ]:
py_list > 3

TypeError: '>' not supported between instances of 'list' and 'int'

**Arrays**

**Example 1**

In [ ]:
np_array == 3

array([False, False,  True, False, False])

**Example 2**

In [ ]:
np_array > 3

array([False, False, False,  True,  True])

In [ ]:
sum(np_array > 3)  # Adds 0 + 0 + 0 + 1 + 1

2

## 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Example 1**

**Lists**

In [ ]:
sum(py_list)

15

**Arrays**

In [ ]:
np_array.sum()

15

**Example 2**

**Lists**

In [ ]:
max(py_list)

5

**Arrays**

In [ ]:
np_array.max()

5

**Example 3**

**Lists**

In [ ]:
min(py_list)

1

**Arrays**

In [ ]:
np_array.min()

1

**Example 4**

**Lists**

In [ ]:
py_list.sum()  # Will not work

AttributeError: 'list' object has no attribute 'sum'

**Arrays**

In [ ]:
np_array.mean()

3.0

**Example 5**

**Arrays**

In [ ]:
np_array.std()

1.4142135623730951

## Footnotes